language: node_js
node_js:
- 4.2.6
env:
  global:
    - secure: "jUReh+2FMkgqS41NzZMnGlsGTddGP/2H5ZMLmk+3z07FRAukWl/RDPyim91T8dLmkZyLUTgc7k55MadjUfmEOt0iFe+lL3v17gyEMrVVNwXSAksFGaaxGo3GqsEFeWKYq6uYnaxedK7PYROnBFHAmTv2E16e9o0rQgFgIf9F7p0bWYXFMmabFkgRZgHnAK99uOH0iOVxjShKhZ6r3EYSVJUfxwmM50fYfiHGhljK21W8IdqJXURRuUVq06Nm9jPubmDgJ/xhT8VBT+x4oVEJEsu4r0E+8y0UiVBP0jrzLY+2bsiY7Bw6gaIHbwczzmsRckSjQbnBBr7taog/SyIFKqWMV4xHPXjEVYsUmLSwRKoVU9US0S80UmYfunZmQGwKmUzMCwmdcq7Irfd2qWKOc0OsBATJzeHzYJ+Mh56UvXqgUyp5o4IsdvZb+vzSbDH51j+diqAjg+EVqCGTQC5ENq7xIrkNxCsbECknJmxMM55JFj4gx0OLdtHA/Zp6MZYaXO95BgO5gP831riuOIqKxfcCjyRK2wl4InfJ2H/6tKvjGA27RwUYkOb/vRH0THpi2NMnV5S+repA9EWo3Fa+SyxJq1YlZSxL9XaJmfrz/RcJewuMCvfu3TU+yzMT4+t4XB3y/0q8SuWyOCwZfYWll+WgbdGBvE6z4ptw975yfo4="
before_script:
- sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py |
  sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read());
  main()"
- npm install gitbook-cli -g
- npm install svgexport -g
- gitbook install
- npm install
script:
- npm run lint-md
- gitbook build
- gitbook pdf ./ ./sapientiae.pdf
- gitbook epub ./ ./sapientiae.epub
- gitbook mobi ./ ./sapientiae.mobi
deploy:
  provider: releases
  api_key:
    secure: ppQLzavb3In25lDNqtEyoruWBjVmw2l9G9359E6vAa9DcgjAAI4DZ0n9PmDUDey1uBP2yz9N83xOB/g2zd5de6m/TfJ7jUyu9Ll0sBfeckvLSp33EA69a+f3fnBmuynDJZxigz5PisX8+i0BeicO6Af0ncq/JT1Qlf5dSq68hb3zrY6Q0PjeyK5l2gqC8+xRoRPB4ZI9630Gr7Jge1EX0mJBTgR0N/Dce5yMNUWsU5PVlHCfmpbMP4tETpg3bH9ZQqsx5h6+7d4z5bCfp0QyjoxD4pw07aKOzS/nlx0IhupO9HlDI9y7nl/8nIU3EE7eXwDiQ58wYbHsKND/j/IYWPIVjWXR2SFq8cMsm6XuF3LtRjFRiUe+7B47m0W497rFWb164NoGXxcwLNueyGmz13adI0SBrD30CnqC3qSuLNd0acnhm8jXaYyK9L7V6ihu3hjLsL9llyRoC5cu0SUMSw4ztqSV/4q3UBKzmu7EEpdWwDAqhT4Lqs+UvuHKdxd6BRp9+cLAMR/YoNqIfLryhlm5InW1WA2VKtjH90/FHrFUgccAoMVok22upp/Zw0rzy4tRC3gSjo9AgdVbwq6rxTJCK2h+2/5D1vkBGNTLxKUKzusgu2+Cvxl3Yc0bqh5Yoi2FvWF5kY5DodnIBgJ8ZKOGsj/W6MJpQ/ldmHJtOHI=
  file: sapientiae.pdf
  skip_cleanup: true
  on:
    tags: true
  provider: pages
  local_dir: _book
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
