language: node_js
node_js:
  - "4.2.6"

before_script:
  - apt install npm
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - gitbook install
  - npm install

script:
  - npm run lint-md
  - gitbook build
  - gitbook pdf ./ ./sapientiae.pdf
  - gitbook epub ./ ./sapientiae.epub
  - gitbook mobi ./ ./sapientiae.mobi
