language: node_js
node_js:
- 4.2.6
before_script:
- sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py |
  sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read());
  main()"
- npm install gitbook-cli -g
- npm install svgexport -g
- gitbook install
- npm install
script:
- npm run lint-md
- gitbook build
- gitbook pdf ./ ./sapientiae.pdf
- gitbook epub ./ ./sapientiae.epub
- gitbook mobi ./ ./sapientiae.mobi
deploy:
  provider: releases
  api_key:
    secure: KPuCFDc3Zs0toYBNnewxztWtAzrJ09H1kpVGuP+zgf1VJ623C/AeXq6YYHsStCXZiUmAVoFeeP8jmse9jOJ3TKz1O20Q5a65n2vrtaa9X7G38gPUlfACAFgY+coAVAItd2hPlIiPqrRRrDYDnu0Xsyxnd9Om+Mzw2Crwhfdfp8XBX3S2CnXd/uFGaCaN27WbtXOyVfVP3kDDRcwmLRGA8qj2vsKyloFV8uD1mwuDo2oaIU+16ER8GO9eKiRRl7egCA4mW+9tNMiHnewYsRTcKs79CmV4MUZ6Kgg78wq7ArJ0knQiNB5NfhJkd/mBr1XpX5nuGCxkeRJyIS46OLM+mo1bSF1ho7CC3Jz8JW7rJdSlIM+lbqqE7GnXuFb0i3r/biWievIhADd2MoEUhVINhUL+XhRw/gN4UXmPqC+zHIx0ACKEaTsYDHBIAz0fcjO1KGokwluH0JjiLxgPedJTvCX+AoD435bk1qwyH3nnKxCc/QXsYvhzsacRLecwA/TRJwb5ybHqigCrdHv0FgezbLy9p/cwHsQQl7WpksjsiTMPIxNSlpInYejYsCvpoh0oRwkHcVONoSTpx5rzumOLh2RiyBHb+/HTuwh6iBeRpJJmaqk2hnti9vGzSt7nOR66ej1VnGQUiA/6VzbrYmHNE2fDFYmafSC5kmo51tmIukE=
  file: sapientiae.pdf
  skip_cleanup: true
  on:
    tags: true
